# External plugins
# See http://ixti.net/software/2013/01/28/using-jekyll-plugins-on-github-pages.html for making `jekyll archives` work.
plugins:
  - jekyll-archives # Sorry, not GitHub pages friendly!
  - jekyll-sitemap
  - jekyll-paginate-v2

exclude:
  - "/vendor/"

# Site settings
title: Clean place's Blog
subtitle: "살바도르 달리의 꿈은 살바도르 달리가 되는 것이었다"
email: marine_k@naver.com
name: Clean Place
description: >
  평범한 NLP 블로거
# Base URL of site (i.e. /blog). It should always start with a slash,
# and never end with a slash. Set it to a blank value if hosting at the
# root of your server.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://cleanplace.github.io/" # the base hostname & protocol for your site
cover: "/assets/image_main.jpg"
logo: "/assets/logo.png"

# Build settings
markdown: kramdown
inter_post_navigation: false
highlightjs_theme: "monokai-sublime"

# Pagination Settings
# https://github.com/sverrirs/jekyll-paginate-v2/blob/master/README-GENERATOR.md#site-configuration
pagination:
  enabled: true
  per_page: 5
  permalink: "/page/:num/"
  sort_reverse: true

# Archive settings (see https://github.com/jekyll/jekyll-archives/)
jekyll-archives:
  enabled:
    - categories
    - tags
  layout: 'archive'
  permalinks:
    category: '/category/:name/'
    tag: '/tag/:name/'

# Category descriptions (for archive pages)
descriptions:
  - cat: NLP
    desc: 자연어 처리의 모든 것

  - cat: Math for AI
    desc: 인공지능을 위한 수학

  - cat: Algorithm
      desc: 재미로 공부하는 알고리즘 이론

social:

  - name: GitHub
    icon: github
    username: clean place
    url: https://github.com/cleanplace
    desc: Fork me on GitHub
    share: false


protocols:
    fb_image: "/assets/logo.png"
    fb_image_width: 612
    fb_image_height: 605
    fb_image_type: "image/png"

    twitter_image: "/assets/logo.png"

    os_repo: "https://github.com/bencentra/centrarium.com"
    os_rcs_type: "git"
    os_src: "git@github.com:bencentra/centrarium.com.git"
